MyApp.AspNetCoreMvcEnterprise/src/Enterprise.App/ViewModels/ProductViewModel.cs
using Enterprise.App.Extensions;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Enterprise.App.ViewModels
{
    public class ProductViewModel
    {
        [Key]
        public Guid Id { get; set; }
        public SupplierViewModel Supplier { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [Display(Name = "Fornecedor")]
        public Guid SupplierId { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(255, ErrorMessage = "O campo {0} deve ter entre {1} e {2} caracteres", MinimumLength = 2)]
        public string Nome { get; set; }

        [Display(Name = "Descrição")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(100, ErrorMessage = "O campo {0} deve ter entre {1} e {2} caracteres", MinimumLength = 2)]
        public string Descricao { get; set; }

        [Display(Name = "Imagem")]
        public IFormFile ImageUpload { get; set; }
        public string Image { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [Coin]
        public decimal Valor { get; set; }

        [ScaffoldColumn(false)]
        public DateTime DataCadastro { get; set; }

        [Display(Name = "Ativo?")]
        public bool Ativo { get; set; }

        public IEnumerable<SupplierViewModel> SupplierList { get; set; }
    }
}

MyApp.AspNetCoreMvcEnterprise/src/Enterprise.App/Controllers/ProductController.cs
using AutoMapper;
using Enterprise.App.Extensions;
using Enterprise.App.ViewModels;
using Enterprise.Business.Interfaces;
using Enterprise.Business.Interfaces.Repository;
using Enterprise.Business.Interfaces.Service;
using Enterprise.Business.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace Enterprise.App.Controllers
{
    [Authorize]
    [Route("Produtos")]
    public class ProductController : BaseController
    {
        private readonly IProductRepository _productRepository;
        private readonly ISupplierRepository _supplierRepository;
        private readonly IProductService _productService;

        public ProductController(IMapper mapper, INotification notification, IProductRepository productRepository, 
            ISupplierRepository supplierRepository, IProductService productService) : base(mapper, notification)
        {
            _productRepository = productRepository;
            _supplierRepository = supplierRepository;
            _productService = productService;
        }
        
        [AllowAnonymous]
        [Route("lista-produtos")]        
        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<ICollection<ProductViewModel>>(await _productRepository.FindAll()));
        }
        
        [AllowAnonymous]
        [Route("detalhes-produto/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            var supplier = await FindProduct(id);
            if (supplier is null) return NotFound();

            return View(supplier);
        }

        [Route("novo-produto")]
        [ClaimsAuthorize("Product","Insert")]
        public async Task<IActionResult> Create()
        {
            ProductViewModel viewModel = await PopularSupplier(new ProductViewModel());
            return View(viewModel);
        }

        [HttpPost]
        [Route("novo-produto")]
        [ClaimsAuthorize("Product", "Insert")]        
        public async Task<IActionResult> Create(ProductViewModel viewModel)
        {
            viewModel = await PopularSupplier(viewModel);
            if (!ModelState.IsValid) return View(viewModel);

            var imgPath = Guid.NewGuid().ToString() + Path.GetExtension(viewModel.ImageUpload.FileName);

            if (!await UploadFile(viewModel.ImageUpload, imgPath)) return View(viewModel);

            viewModel.Image = imgPath;

            await _productService.Insert(_mapper.Map<Product>(viewModel));

            if (OperationIsValid()) return View(viewModel);

            return RedirectToAction(nameof(Index));
        }

        [Route("editar-produto/{id:guid}")]
        [ClaimsAuthorize("Product", "Edit")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var supplier = await FindProduct(id);
            if (supplier is null) return BadRequest();
            return View(supplier);
        }

        [HttpPost]
        [Route("editar-produto/{id:guid}")]
        [ClaimsAuthorize("Product", "Edit")]        
        public async Task<IActionResult> Edit(Guid id, ProductViewModel viewModel)
        {
            if (id != viewModel.Id) return NotFound();

            var productUpdate = await FindProduct(id);
            viewModel.Supplier = productUpdate.Supplier;
            viewModel.Image = productUpdate.Image;
            if (!ModelState.IsValid) return View(viewModel);

            if (viewModel.ImageUpload != null)
            {
                var imgPath = Guid.NewGuid().ToString() + Path.GetExtension(viewModel.ImageUpload.FileName);
                if (!await UploadFile(viewModel.ImageUpload, imgPath)) return View(viewModel);
                productUpdate.Image = imgPath;
            }
            productUpdate.Nome = viewModel.Nome;
            productUpdate.Valor = viewModel.Valor;
            productUpdate.Descricao = viewModel.Descricao;
            productUpdate.Ativo = viewModel.Ativo;

            await _productService.Update(_mapper.Map<Product>(productUpdate));

            if (OperationIsValid()) return View(viewModel);

            return RedirectToAction(nameof(Index));
        }

        [ClaimsAuthorize("Product", "Remove")]
        [Route("excluir-produto/{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var product = await FindProduct(id);
            if (product is null) return BadRequest();
            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        [ClaimsAuthorize("Product", "Remove")]
        [Route("excluir-produto/{id:guid}")]        
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var db = await FindProduct(id);
            if (db is null) return BadRequest();

            await _productService.Delete(id);

            if (OperationIsValid()) return View(db);
            TempData["Sucesso"] = "Produto excluido com sucesso!";
            return RedirectToAction(nameof(Index));
        }

        private async Task<ProductViewModel> FindProduct(Guid id)
        {
            var product = _mapper.Map<ProductViewModel>(await _productRepository.FindProductSupplier(id));
            product.SupplierList = _mapper.Map<IEnumerable<SupplierViewModel>>(await _supplierRepository.FindAll());
            return product;
        }

        private async Task<ProductViewModel> PopularSupplier(ProductViewModel viewModel)
        {
            viewModel.SupplierList = _mapper.Map<IEnumerable<SupplierViewModel>>(await _supplierRepository.FindAll());
            return viewModel;
        }

        private async Task<bool> UploadFile(IFormFile imageUpload, string imgPath)
        {
            if (imageUpload.Length <= 0) return false;

            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/image", imgPath);

            if (System.IO.File.Exists(path))
            {
                ModelState.AddModelError(string.Empty, "Já existe um arquivo com este nome");
                return false;
            }

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await imageUpload.CopyToAsync(stream);
            }

            return true;
        }
    }
}

MyApp.AspNetCoreMvcEnterprise/src/Enterprise.App/Extensions/SummaryViewComponent.cs
using Enterprise.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Enterprise.App.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly INotification _notification;

        public SummaryViewComponent(INotification notification)
        {
            _notification = notification;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notifier = await Task.FromResult(_notification.FindAll());

            notifier.ForEach(x => ViewData.ModelState.AddModelError(string.Empty, x.Message));

            return View(notifier);
        }
    }
}

MyApp.AspNetCoreMvcEnterprise/src/Enterprise.App/Views/Product/Create.cshtml
@model Enterprise.App.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "Novo Produto";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SupplierId" class="control-label"></label>
                <select asp-for="SupplierId" class="form-control" asp-items="@(new SelectList(Model.SupplierList,"Id","Nome"))">
                    <option></option>
                </select>
                <span asp-validation-for="SupplierId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <textarea rows="5" asp-for="Descricao" class="form-control"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUpload" class="control-label"></label>
                <div class="custom-file">
                    <input type="file" class=" custom-file-input"  id="ImageUpload" asp-for="ImageUpload"/>
                    <label data-browser="procurar" style="width:350px" class=" custom-file-label" for="ImageUpload"></label>
                    <label style="display:none" id="img_nome"></label>
                </div>


                <span asp-validation-for="ImageUpload" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-outline-primary" />
                <a class="btn btn-outline-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $("#ImageUpload").change(function () {
            $("#img_nome").text(this.files[0].name);
            $("#img_nome")[0].style.display = 'block';
        });

        $("#ImageUpload").attr("data-val", "true");
        $("#ImageUpload").attr("data-val-required", "Preencha o campo Imagem");
    </script>

}

MyApp.AspNetCoreMvcEnterprise/src/Enterprise.App/Views/Product/Delete.cshtml
@model Enterprise.App.ViewModels.ProductViewModel
@{
    ViewData["Title"] = "Excluir " + Model.Nome;
}
<h4 style="padding-top: 50px">@ViewData["Title"]</h4>

<h5>Você tem certeza disso?</h5>

<div class="row">
    <div class="col-md-4">
        <img src="~/Image/@Model.Image" alt="Imagem do Produto" style="width:300px; height:428px" />
    </div>
    <div class="col-md-6">
        <dl>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Supplier)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Supplier.Documento)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Nome)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Nome)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Descricao)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Descricao)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Image)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Image)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Valor)
            </dt>
            <dd class="col-sm-10">
                @Model.Valor.ToString("C")
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Ativo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Ativo)
            </dd>
        </dl>
    </div>

</div>
<br />
<form asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <input class="btn btn-outline-danger" type="submit" value="Delete"/> |
    <a class="btn btn-outline-info" href="javascript:window.history.back();">Voltar</a>
</form>

MyApp.AspNetCoreMvcEnterprise/src/Enterprise.App/Views/Product/Details.cshtml
@model Enterprise.App.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "Detalhes do Produto - " + Model.Nome;
}

<h4 style="padding-top:50px">@ViewData["Title"]</h4>

<div class="row">
    <div class="col-md-4">
        <img src="~/Image/@Model.Image" alt="Imagem do Produto" style="width:300px; height:428px" />
    </div>
    <div class="col-md-6">
        <dl>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Supplier)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Supplier.Documento)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Nome)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Nome)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Descricao)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Descricao)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Image)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Image)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Valor)
            </dt>
            <dd class="col-sm-10">
                @Model.Valor.ToString("C")
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Ativo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Ativo)
            </dd>
        </dl>
    </div>

</div>
<br />
<div class="form-group">
    <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    <a class="btn btn-outline-info" href="javascript:window.history.back();">Voltar</a>
</div>

MyApp.AspNetCoreMvcEnterprise/src/Enterprise.App/Views/Product/Edit.cshtml
@model Enterprise.App.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "Editar " + Model.Nome;
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="SupplierId" class="control-label"></label>
                <label><b>@Model.Supplier.Nome</b></label>                
            </div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <textarea rows="5" asp-for="Descricao" class="form-control"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label><br />
                <img src="~/Image/@Model.Image" alt="Alternate Text" style="width:70px; height:100px" />
            </div>
            <div class="form-group">
                <label asp-for="ImageUpload" class="control-label"></label>
                <div class="custom-file">
                    <input type="file" class=" custom-file-input" id="ImageUpload" asp-for="ImageUpload" />
                    <label data-browser="procurar" style="width:350px" class=" custom-file-label" for="ImageUpload"></label>
                    <label style="display:none" id="img_nome"></label>
                </div>


                <span asp-validation-for="ImageUpload" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-outline-primary" />
                <a class="btn btn-outline-info" href="javascript:window.history.back();">Voltar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
            $("#ImageUpload").change(function () {
                $("#img_nome").text(this.files[0].name);
                $("#img_nome")[0].style.display = 'block';
            });
    </script>
}

MyApp.AspNetCoreMvcEnterprise/src/Enterprise.App/Views/Product/Index.cshtml
@model IEnumerable<Enterprise.App.ViewModels.ProductViewModel>

@{
    ViewData["Title"] = "Lista de Produtos";
}

<h1>@ViewData["Title"]</h1>
<vc:summary></vc:summary>
<p >
    <a disable-by-claim-name="Supplier" disable-by-claim-value="Insert" class="btn btn-outline-info" asp-action="Create">Novo Produto</a>
</p>

<partial name="_ListProduct" />

MyApp.AspNetCoreMvcEnterprise/src/Enterprise.App/Views/Product/_ListProduct.cshtml
@model IEnumerable<Enterprise.App.ViewModels.ProductViewModel>

<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SupplierId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="~/Image/@item.Image" alt="Alternate Text" style="width:40px; height:40px" />
                    
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Supplier.Documento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>

                <td>
                    @item.Valor.ToString("C")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ativo)
                </td>
                <td class="text-right">
                    <a disable-by-claim-name="Supplier" disable-by-claim-value="Details" class="btn btn-outline-info" asp-controller="Product" asp-action="Details" asp-route-id="@item.Id"><span class="fa fa-search"></span></a> 
                    <a disable-by-claim-name="Supplier" disable-by-claim-value="Edit" class="btn btn-outline-warning" asp-controller="Product" asp-action="Edit" asp-route-id="@item.Id"><span class="fa fa-pencil-alt"></span></a> 
                    <a disable-by-claim-name="Supplier" disable-by-claim-value="Remove" class="btn btn-outline-danger" asp-controller="Product" asp-action="Delete" asp-route-id="@item.Id"><span class="fa fa-trash-alt"></span></a>
                </td>
            </tr>
        }
    </tbody>
</table>